PLATFORM_TRS80_M100 = 'trs80_m100'
PLATFORM_ZX_SPECTRUM = 'zx_spectrum'
SCREEN_TITLE_MAX_LENGTH = 20
SCREEN_TITLE_BYTES = SCREEN_TITLE_MAX_LENGTH + 1
MAX_INTERACTABLES = 10
BACKGROUND_COLS = 20
BACKGROUND_ROWS = 8

TILE_CHARACTERS = ' !"#$%&\'()+,-./0123456789:;<=>?@|\\[]_{}~`'
TILE_CHARACTERS = TILE_CHARACTERS + 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
TILE_CHARACTERS = TILE_CHARACTERS + '▛▜▙▟▌▐▀▄█▘▝▗▖▚▞▔▂▓┌┐└┘│─┬├┴┤┼◤◥◣◢'
TILE_CHARACTERS = TILE_CHARACTERS + '↕◇✝⌂£¶옷왓∩€ㅑ'
